### ISSUE TITLE
Not a issue, consideration about TODO

### ISSUE THREAD

**Issue by gartz** [hash-bang/async-chainable#2]
Hey @hash-bang I think you should keep using `next` as a parameter and not use the context to expose it.

If you use a binded function as callback, you can't set the context, so the `next` method will be missing in that context, and your "promise" will never be resolved.

Anyway, great job! It's very good lib.

**Comment by hash-bang** [comment]
@gartz Thanks for the feedback.

Using next() is prefered behaviour yes but I was thinking of providing additional context functionality such as skip(steps), redo() and other control flows. I doubt the majority of people would use these but I have noticed that nesting asyncChainable instances can get quickly out of control.

Anyway, even if it is implemented the parameter method will not go away, its required for pretty much every other solution anyway.

Glad you like the lib. Let me know if you have any other feature suggestions.

**Comment by gartz** [comment]
You can pass a object with the methods binded to desired context and
provide your method collection in the argument instead the function add it
is now. ☺

On Saturday, May 9, 2015, Matt Carter notifications@github.com wrote:

> @gartz https://github.com/gartz Thanks for the feedback.
> 
> Using next() is prefered behaviour yes but I was thinking of providing
> additional context functionality such as skip(steps), redo() and other
> control flows. I doubt the majority of people would use these but I have
> noticed that nesting asyncChainable instances can get quickly out of
> control.
> 
> Anyway, even if it is implemented the parameter method will not go away,
> its required for pretty much every other solution anyway.
> 
> Glad you like the lib. Let me know if you have any other feature
> suggestions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hash-bang/async-chainable/issues/2#issuecomment-100554848
> .

## 

Sent from Gmail Mobile
